sudo: required
service:
  - docker

before_install:
  - docker build -t nikunjgupta9/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true nikunjgupta9/react-test npm test

after_success:
  - docker build -t nikunjgupta9/multi-client ./client
  - docker build -t nikunjgupta9/multi-nginx ./nginx
  - docker build -t nikunjgupta9/multi-server ./server
  - docker build -t nikunjgupta9/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push nikunjgupta9/multi-client
  - docker push nikunjgupta9/multi-nginx
  - docker push nikunjgupta9/multi-server
  - docker push nikunjgupta9/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-061327679792"
  bucket_path: "docker-multi"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY