version: '3'
services:
  server:
    image: "nikunjgupta9/multi-server"
    hostname: api
    mem_limit: 128m
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432      
  client:
    image: "nikunjgupta9/multi-client"
    hostname: client
    mem_limit: 128m 
  worker:
    image: "nikunjgupta9/multi-worker"
    hostname: worker
    mem_limit: 128m
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
  nginx:
    image: "nikunjgupta9/multi-nginx"
    hostname: nginx
    mem_limit: 128m
    ports:
      - "80:80"

